"use client"

import { Suspense, lazy, useMemo } from "react"
import { parseAsString, parseAsStringLiteral, useQueryStates } from "nuqs"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Link2 } from "lucide-react"
import { ToolHeader } from "@/components/ui/tool-header"
import {
  URL_ENCODING_REFERENCE,
  deserializeParams,
  serializeParams,
  splitUrl,
  type UrlEncodeMode,
} from "@/lib/url-encode"

// one chunk per tab: the builder is not downloaded to encode a single string
const EncodePanel = lazy(() => import("./encode").then((m) => ({ default: m.EncodePanel })))
const DecodePanel = lazy(() => import("./decode").then((m) => ({ default: m.DecodePanel })))
const BuildPanel = lazy(() => import("./build").then((m) => ({ default: m.BuildPanel })))

const MODES = ["encode", "decode", "build"] as const
const ENCODINGS = ["component", "uri", "form", "rfc3986"] as const
type Mode = (typeof MODES)[number]

function PanelFallback() {
  return (
    <p
      data-panel-fallback
      className="text-muted-foreground rounded-lg border border-dashed p-6 text-center text-sm"
    >
      Loading...
    </p>
  )
}

export function URLEncoder() {
  // a url is short and never a secret, so unlike base64 and json it goes in the query string
  const [query, setQuery] = useQueryStates(
    {
      mode: parseAsStringLiteral(MODES).withDefault("encode"),
      enc: parseAsStringLiteral(ENCODINGS).withDefault("component"),
      q: parseAsString.withDefault(""),
      base: parseAsString.withDefault("https://example.com/path"),
      params: parseAsString.withDefault("search=hello+world&page=1"),
    },
    { history: "replace" }
  )

  const { mode, enc, q, base, params: serializedParams } = query
  const params = useMemo(() => {
    const parsed = deserializeParams(serializedParams)
    return parsed.length > 0 ? parsed : [{ key: "", value: "" }]
  }, [serializedParams])

  const setEncoding = (encoding: UrlEncodeMode) => void setQuery({ enc: encoding })
  const setText = (text: string) => void setQuery({ q: text })

  const parseIntoBuilder = () => {
    const split = splitUrl(q)
    if (!split) return
    void setQuery({
      mode: "build",
      base: split.base,
      params: serializeParams(split.params.length > 0 ? split.params : [{ key: "", value: "" }]),
    })
  }

  return (
    <div className="tool-container">
      <ToolHeader
        icon={Link2}
        title="URL Encoder/Decoder"
        description="Percent-encode, decode and build URLs, with the right encoding for each job"
      />

      <Tabs value={mode} onValueChange={(value) => setQuery({ mode: value as Mode })}>
        <Card>
          <CardHeader>
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div>
                <CardTitle>URL Tool</CardTitle>
                <CardDescription>Encode, decode or assemble a URL</CardDescription>
              </div>
              <TabsList aria-label="URL tool mode">
                <TabsTrigger value="encode">Encode</TabsTrigger>
                <TabsTrigger value="decode">Decode</TabsTrigger>
                <TabsTrigger value="build">Build URL</TabsTrigger>
              </TabsList>
            </div>
          </CardHeader>
          <CardContent>
            <TabsContent value="encode">
              <Suspense fallback={<PanelFallback />}>
                <EncodePanel
                  encoding={enc}
                  onEncodingChange={setEncoding}
                  text={q}
                  onTextChange={setText}
                />
              </Suspense>
            </TabsContent>

            <TabsContent value="decode">
              <Suspense fallback={<PanelFallback />}>
                <DecodePanel
                  encoding={enc}
                  onEncodingChange={setEncoding}
                  text={q}
                  onTextChange={setText}
                  onParseIntoBuilder={parseIntoBuilder}
                />
              </Suspense>
            </TabsContent>

            <TabsContent value="build">
              <Suspense fallback={<PanelFallback />}>
                <BuildPanel
                  base={base}
                  onBaseChange={(value) => setQuery({ base: value })}
                  params={params}
                  onParamsChange={(value) => setQuery({ params: serializeParams(value) })}
                />
              </Suspense>
            </TabsContent>
          </CardContent>
        </Card>
      </Tabs>

      <Card>
        <CardHeader>
          <CardTitle>URL Encoding Reference</CardTitle>
          <CardDescription>
            Generated by running each character through the encoders themselves, so it cannot drift
            from what the tool does
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <caption className="sr-only">
                How each character is encoded by encodeURIComponent, encodeURI, form-urlencoded and
                strict RFC 3986
              </caption>
              <thead>
                <tr className="border-b text-left">
                  <th scope="col" className="p-2 font-semibold">
                    Char
                  </th>
                  <th scope="col" className="p-2 font-semibold">
                    encodeURIComponent
                  </th>
                  <th scope="col" className="p-2 font-semibold">
                    encodeURI
                  </th>
                  <th scope="col" className="p-2 font-semibold">
                    form-urlencoded
                  </th>
                  <th scope="col" className="p-2 font-semibold">
                    RFC 3986
                  </th>
                </tr>
              </thead>
              <tbody>
                {URL_ENCODING_REFERENCE.map((row) => (
                  <tr key={row.char} className="border-b last:border-0">
                    <th scope="row" className="p-2 text-left font-mono font-normal">
                      {row.char === " " ? (
                        <span className="text-muted-foreground">space</span>
                      ) : (
                        row.char
                      )}
                    </th>
                    <td className="p-2 font-mono text-xs">{row.component}</td>
                    <td className="p-2 font-mono text-xs">{row.uri}</td>
                    <td className="p-2 font-mono text-xs">{row.form}</td>
                    <td className="p-2 font-mono text-xs">{row.rfc3986}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-muted-foreground mt-3 text-xs">
            encodeURIComponent leaves <code className="font-mono">! &apos; ( ) *</code> unescaped
            even though RFC 3986 2.2 reserves them as sub-delims. That is the one difference between
            the first and last columns.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
