name: Question
description: Ask a question about NetDash Toolkit usage or functionality
title: "[Question]: "
labels: ["question", "support"]
assignees:
  - sunnypatell
body:
  - type: markdown
    attributes:
      value: |
        Have a question about NetDash Toolkit? We're here to help! Please provide as much context as possible.

        > **Note:** For general discussions, consider using [GitHub Discussions](https://github.com/sunnypatell/netdash-toolkit/discussions) instead.

  - type: checkboxes
    id: checklist
    attributes:
      label: Before asking
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for my question
          required: true
        - label: I have read the README and documentation
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What area does your question relate to?
      options:
        - Installation / Setup
        - Tool Usage
        - Configuration
        - Networking Concepts
        - Desktop App (Electron)
        - Web Version
        - Development / Contributing
        - Other
      default: 1
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform (if applicable)
      description: Which platform are you using?
      options:
        - Not applicable
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Linux
        - Web Browser
      default: 0

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail.
      placeholder: |
        I'm trying to understand how to...

        What I've tried:
        - Step 1
        - Step 2

        What I expected:
        ...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or code snippets that might help.

  - type: dropdown
    id: urgency
    attributes:
      label: How urgent is this?
      description: This helps us prioritize responses
      options:
        - Not urgent - just curious
        - Moderate - would like to know soon
        - High - blocking my work
      default: 0
