import type { PortEntry } from "./types"

// checked row by row against the iana service name and transport protocol port
// number registry (service-names-port-numbers.csv). where the everyday name and
// the registered name disagree, ianaName carries the registered one so the table
// can show both instead of presenting folklore as an assignment.
export const COMMON_PORTS: readonly PortEntry[] = [
  {
    port: 20,
    protocol: "TCP",
    service: "FTP Data",
    ianaName: "ftp-data",
    description: "File Transfer Protocol data channel",
  },
  {
    port: 21,
    protocol: "TCP",
    service: "FTP Control",
    ianaName: "ftp",
    description: "File Transfer Protocol control/command channel",
  },
  {
    port: 22,
    protocol: "TCP",
    service: "SSH",
    ianaName: "ssh",
    description: "Secure Shell, secure remote login (RFC 4253)",
  },
  {
    port: 23,
    protocol: "TCP",
    service: "Telnet",
    ianaName: "telnet",
    description: "Unencrypted remote login (legacy)",
  },
  {
    port: 25,
    protocol: "TCP",
    service: "SMTP",
    ianaName: "smtp",
    description: "Simple Mail Transfer Protocol, server to server relay",
  },
  {
    port: 53,
    protocol: "TCP/UDP",
    service: "DNS",
    ianaName: "domain",
    description: "Domain Name System; UDP for queries, TCP for large answers and zone transfers",
  },
  {
    port: 67,
    protocol: "UDP",
    service: "DHCP Server",
    ianaName: "bootps",
    description: "DHCP/BOOTP server port; registered as bootps",
  },
  {
    port: 68,
    protocol: "UDP",
    service: "DHCP Client",
    ianaName: "bootpc",
    description: "DHCP/BOOTP client port; registered as bootpc",
  },
  {
    port: 69,
    protocol: "UDP",
    service: "TFTP",
    ianaName: "tftp",
    description: "Trivial File Transfer Protocol",
  },
  {
    port: 80,
    protocol: "TCP",
    service: "HTTP",
    ianaName: "http",
    description: "Hypertext Transfer Protocol",
  },
  {
    port: 110,
    protocol: "TCP",
    service: "POP3",
    ianaName: "pop3",
    description: "Post Office Protocol version 3",
  },
  {
    port: 119,
    protocol: "TCP",
    service: "NNTP",
    ianaName: "nntp",
    description: "Network News Transfer Protocol",
  },
  {
    port: 123,
    protocol: "UDP",
    service: "NTP",
    ianaName: "ntp",
    description: "Network Time Protocol",
  },
  {
    port: 137,
    protocol: "UDP",
    service: "NetBIOS Name",
    ianaName: "netbios-ns",
    description: "NetBIOS Name Service",
  },
  {
    port: 138,
    protocol: "UDP",
    service: "NetBIOS Datagram",
    ianaName: "netbios-dgm",
    description: "NetBIOS Datagram Service",
  },
  {
    port: 139,
    protocol: "TCP",
    service: "NetBIOS Session",
    ianaName: "netbios-ssn",
    description: "NetBIOS Session Service, SMB over NetBIOS",
  },
  {
    port: 143,
    protocol: "TCP",
    service: "IMAP",
    ianaName: "imap",
    description: "Internet Message Access Protocol; 143/udp is reserved",
  },
  {
    port: 161,
    protocol: "UDP",
    service: "SNMP",
    ianaName: "snmp",
    description: "Simple Network Management Protocol queries",
  },
  {
    port: 162,
    protocol: "UDP",
    service: "SNMP Trap",
    ianaName: "snmptrap",
    description: "SNMP trap and notification messages",
  },
  {
    port: 389,
    protocol: "TCP/UDP",
    service: "LDAP",
    ianaName: "ldap",
    description: "Lightweight Directory Access Protocol",
  },
  {
    port: 443,
    protocol: "TCP",
    service: "HTTPS",
    ianaName: "https",
    description: "HTTP over TLS",
  },
  {
    port: 445,
    protocol: "TCP",
    service: "SMB",
    ianaName: "microsoft-ds",
    description: "SMB directly over TCP, no NetBIOS session layer",
  },
  {
    port: 465,
    protocol: "TCP",
    service: "SMTPS",
    ianaName: "submissions",
    description:
      "Mail submission over implicit TLS, current practice per RFC 8314; IANA also lists urd here",
  },
  {
    port: 500,
    protocol: "UDP",
    service: "IKE",
    ianaName: "isakmp",
    description: "Internet Key Exchange for IPsec; registered as isakmp",
  },
  {
    port: 514,
    protocol: "UDP",
    service: "Syslog",
    ianaName: "syslog",
    description: "System logging (RFC 5426); 514/tcp is registered to shell (rsh), not syslog",
  },
  {
    port: 587,
    protocol: "TCP",
    service: "SMTP Submission",
    ianaName: "submission",
    description: "Mail submission with STARTTLS (RFC 6409)",
  },
  {
    port: 636,
    protocol: "TCP",
    service: "LDAPS",
    ianaName: "ldaps",
    description: "LDAP over TLS",
  },
  {
    port: 853,
    protocol: "TCP",
    service: "DNS over TLS",
    ianaName: "domain-s",
    description: "DNS over TLS (RFC 7858); 853/udp is DNS over DTLS and QUIC",
  },
  {
    port: 873,
    protocol: "TCP",
    service: "rsync",
    ianaName: "rsync",
    description: "rsync file synchronisation daemon",
  },
  {
    port: 993,
    protocol: "TCP",
    service: "IMAPS",
    ianaName: "imaps",
    description: "IMAP over implicit TLS",
  },
  {
    port: 995,
    protocol: "TCP",
    service: "POP3S",
    ianaName: "pop3s",
    description: "POP3 over implicit TLS",
  },
  {
    port: 1194,
    protocol: "UDP",
    service: "OpenVPN",
    ianaName: "openvpn",
    description: "OpenVPN; also runs over 1194/tcp",
  },
  {
    port: 1433,
    protocol: "TCP",
    service: "MSSQL",
    ianaName: "ms-sql-s",
    description: "Microsoft SQL Server",
  },
  {
    port: 1521,
    protocol: "TCP",
    service: "Oracle DB",
    ianaName: "ncube-lm",
    description: "Oracle TNS listener by convention; IANA assigns 1521 to nCube License Manager",
  },
  {
    port: 1701,
    protocol: "UDP",
    service: "L2TP",
    ianaName: "l2tp",
    description: "Layer 2 Tunneling Protocol (RFC 3931); 1701 is shared with l2f",
  },
  {
    port: 1723,
    protocol: "TCP",
    service: "PPTP",
    ianaName: "pptp",
    description: "Point-to-Point Tunneling Protocol control channel",
  },
  {
    port: 1883,
    protocol: "TCP",
    service: "MQTT",
    ianaName: "mqtt",
    description: "Message Queuing Telemetry Transport",
  },
  {
    port: 2375,
    protocol: "TCP",
    service: "Docker API",
    ianaName: "docker",
    description: "Docker REST API in plain text, unauthenticated; do not expose",
  },
  {
    port: 2376,
    protocol: "TCP",
    service: "Docker API (TLS)",
    ianaName: "docker-s",
    description: "Docker REST API over TLS",
  },
  {
    port: 3000,
    protocol: "TCP",
    service: "Grafana / dev servers",
    ianaName: "hbci",
    description: "Grafana and local dev servers by convention; IANA assigns 3000 to HBCI",
  },
  {
    port: 3306,
    protocol: "TCP",
    service: "MySQL",
    ianaName: "mysql",
    description: "MySQL and MariaDB",
  },
  {
    port: 3389,
    protocol: "TCP",
    service: "RDP",
    ianaName: "ms-wbt-server",
    description: "Remote Desktop Protocol",
  },
  {
    port: 4500,
    protocol: "UDP",
    service: "IPsec NAT-T",
    ianaName: "ipsec-nat-t",
    description: "IPsec NAT traversal (RFC 3948); 4500/tcp is TCP encapsulation (RFC 9329)",
  },
  {
    port: 5222,
    protocol: "TCP",
    service: "XMPP Client",
    ianaName: "xmpp-client",
    description: "XMPP client connection (RFC 6120); 5222/udp is reserved",
  },
  {
    port: 5269,
    protocol: "TCP",
    service: "XMPP Server",
    ianaName: "xmpp-server",
    description: "XMPP server to server connection (RFC 6120)",
  },
  {
    port: 5432,
    protocol: "TCP",
    service: "PostgreSQL",
    ianaName: "postgresql",
    description: "PostgreSQL database",
  },
  {
    port: 5900,
    protocol: "TCP",
    service: "VNC",
    ianaName: "rfb",
    description: "Remote Framebuffer, VNC display :0",
  },
  {
    port: 6379,
    protocol: "TCP",
    service: "Redis",
    ianaName: "redis",
    description: "Redis key-value store; 6379/udp is reserved",
  },
  {
    port: 6443,
    protocol: "TCP",
    service: "Kubernetes API",
    ianaName: "sun-sr-https",
    description:
      "Kubernetes API server by convention; IANA assigns 6443 to Sun Service Registry HTTPS",
  },
  {
    port: 8080,
    protocol: "TCP",
    service: "HTTP Alt",
    ianaName: "http-alt",
    description: "Alternative HTTP port, common for proxies and app servers",
  },
  {
    port: 8443,
    protocol: "TCP",
    service: "HTTPS Alt",
    ianaName: "pcsync-https",
    description: "Alternative HTTPS port by convention; IANA assigns 8443 to pcsync-https",
  },
  {
    port: 8883,
    protocol: "TCP",
    service: "MQTT over TLS",
    ianaName: "secure-mqtt",
    description: "Secure MQTT",
  },
  {
    port: 9090,
    protocol: "TCP",
    service: "Prometheus",
    ianaName: "websm",
    description: "Prometheus by convention; IANA assigns 9090 to WebSM",
  },
  {
    port: 27017,
    protocol: "TCP",
    service: "MongoDB",
    ianaName: "mongodb",
    description: "MongoDB server; 27017/udp is reserved",
  },
  {
    port: 51820,
    protocol: "UDP",
    service: "WireGuard",
    ianaName: "unassigned",
    description:
      "WireGuard default by convention only; 51820 sits in the dynamic range IANA never assigns (RFC 6335 s6)",
  },
]
